### ISSUE TITLE
prisma server down when uploading 

### ISSUE THREAD

**Issue by KarlLeeS** [KarlLeeS/earthrun_backend#1]
situation 
- 프리즈마의 데이터 모델이 변경되어서 이를 최신화하고자 prisma deploy 명령어를 실행한 후에 이와 관련된 코드들을 최신화 한 후에 upload mutation을 작동시켰으나 작동을 하지 않음 

trial 
- 간단한 타이포 에러인가 상세히 살펴보았지만 오타는 없었음
- prisma의 datamodel, prisma-client의 model들, 그리고 graphql-resolver의 필드들을 다 확인하였으나 여전히 에러가 뜸 

solution 
- 아마도 프리즈마 내부 서버의 문제가 아닐까 싶은데, 내일 한번 다 밀어보고 한번 다시 실행을 해봐야 겠다.

**Comment by Songift** [comment]
프리즈마 internal server error가 맞아서. 
프리즈마 전체적으로 밀고 다시 서버 세팅하니까 정상 작동확인했습니다.
