### ISSUE TITLE
Updates were rejected because the tip of your current branch is behind its remote counterpart. Integrate the remote changes (e.g. 'git pull ...') before pushing again. See the 'Note about fast-forwards' in 'git push --help' for details.

### ISSUE THREAD

**Issue by KarlLeeS** [KarlLeeS/earthrun_backend#2]
Situations : Updates were rejected because the tip of your current branch is behind its remote counterpart. Integrate the remote changes (e.g.'git pull ...') before pushing again. See the 'Note about fast-forwards' in 'git push --help' for details. 라는 에러메세지가 나옴

Research: 
구글링 결과, 다음과 같은 내용을 배웠다. 
git은 remote와 local branch라는 컨셉으로 관리되어지는데,
local branch는 내 깃 레파의 로컬 버젼에 존재하는 것, remote branch는 깃 레파의 리모트 위치에 존재하는 것이다.( 일반적으론 remote branch는 origin이다) 그 remote branch는 일반적으로 내 저장소가 호스팅 될 곳이다. 

the tip of your current branch is behind its remote counterpart라는 말은 너가 로컬 브랜치로 가지고 있지 않는 리모트 브랜치에서 변화가 있었다는 이야기이다. 

remote branch에는 2가지 가능성이 있다. 
1. 누군가가 커밋을  추가했거나
2. 누군가가 브랜치 히스토리를 modify했다. ( rebase와 같은 ?) 

Actions : 
일단 git pull 을 해보라고 해서 해봤는데 현재 원격 저장소에 있는 내용 ( 이전 내용)이 imcomming으로 잡히고 내가 새로 작성한 코드가 current로 잡혀서 마치 예전 코드로 돌아가려는 구조가 보인다. 혹시나 코드가 완전 날라가는 불상사를 막기위해서 일단은 지금 작성한 코드를 따로 백업을 해두고서 git을 더 공부해보고 이 문제를 해결해보아야 겠다. 
내가 모르는 기본 개념부터 이것저것 공부할 것이 많아보인다. 
git에서 merge가 될 때 어느 브랜치에서 어느 브랜치로 하는지 이런 기준이 어렵다..

**Comment by Songift** [comment]
# 깨달은 점 

1. 보통 github에 등록된 소스는 fork 기능을 이용해서 내 저장소에 복사한 후 클론하여 작업하고 수정하는 경우가 많다. 바로 clone을 하면 수정권한이 없기 때문이다. 

2. 하지만 opensource에 버그를 발견했다면, pull request를 활용해 수정사항을 전달하여 기여할 수 있다. 

3. 
git pull : 코드를 받아와서 변경점을 merge한다. 
git fetch : 코드를 받아온다 

4. pull과 fetch의 차이는 merge의 유무, fetch는 코드를 받아온 후 즉시 반영하지 않는다. 작업한 코드가 충돌이 일어날 경우에 안전하다. pull은 코드를 받아온 후 즉시 merge해서 충돌이 일어날 수 있다. 이 경우 충돌을 해결해주고 다시 commit한다.

5. Branch 관리 
master에서 branch를 생성하면 master를 기준으로 branch가 생성. 
코드들은 기존 master의 작업과 분리되며, 언제든지 checkout을 통해 master와 branch를 이동하며 코드를 변경할 수 있다. 작업한 branch 내용을 master와 합쳐야 한다면, merge명령어로 가능 
git merge master branch_name 

6. 만약 merge 하려는 2개의 코드에 충돌이 일어난다면? 
git은 merge한 내용 중 충돌하는 내용을 찾아서 수정해달라고 요청하게 된다. 영역의 내용을 모두 수정해준 뒤 git add , git commit 하면 충돌한 merge가 합쳐진다. 

7. git은 코드의 상태를 uncommit / staying / commit 으로 나눠 볼 수 있다. 
1. 코드 파일의 내용을 바꾸면 uncommit이다.
2. 파일의 변경 내역을 add하면 index에 추가되면서 staying
3. 변경 내용을 commit으로 확정지음
4. commit이 완료되면 서버에 push할 수 있음

8. 코드를 작성하다보면 잘못된 코드를 추가 혹은 merge할 수 있다. 취소하려면 
git reset : add 한 파일 취소 
git reset --merge : merge 한 코드 취소 

9. 
git reset HEAD^
commit한 코드를 취소하고 이전 코드로 돌아가고 싶다면, 그러나 이전에 수정했던 코드는 모두 사라짐. 

git reset --sorf HEAD^ 
commit한 코드를 취소하고 작성한 코드를 살리기. 

10. HEAD 
현재 브랜치를 가리키는 포인터, 브랜치는 브랜치에 담긴 커밋 중 마지막 커밋을 가리킨다. 단순하게 HEAD는 마지막 커밋의 스냅샷. 

11. INDEX 
INDEX는 바로 다음에 커밋할 것들, git commit 명령을 실행했을 때, git이 처리할 것들이 있는 대기실
