### ISSUE TITLE
RecommendFriendsLike에서의 비동기처리 문제. 

### ISSUE THREAD

**Issue by KarlLeeS** [KarlLeeS/earthrun_backend#3]
# Situation 

- 사용자의 정보로부터 사용자의 following list를 가지고 온 후에, 다시 following list의 likes를 가지고 온 후, 그 likes의 postid를 가지고 오는 deep qeury 문을 구현하는 과정에서 전체 쿼리를 모두 기다려야 하는 문제를 해결하지 못하고 있습니다. 

- 필요한 정보를 데이터베이스에서 채 다 가지고 오기도 전에 함수가 끝나버립니다. 

# Action 

- async await promise에 대한 기본적인 개념 정리를 해보고 Promise.all 이라는 메소드로 해결을 해야 한다는 것을 알았습니다. 
- 이게 async await으로 단순히 1회 호출 후 반복문 처리까지만 생각하면은 쉽지만 그 반복문의 어떠한 값을 처리를 기다려야 하는 상황에서는 promise에 대한 이해가 더욱 필요하다고 생각에 이런저런... 코드들을 써보고 돌려보고 확인하는 과정을 가졌습니다. 

# Result 
- 꽤나 복잡한 코드가 되어버렸는데, 설명을 하면 
1. user의 follow list를 기다리는 promise.all 
2. follow list에서 뽑아낸 users들의 likes를 기다려주는 promise.all
3. 2개의 promise가 끝난 후 가벼운 연산 처리를 기다려주기 위한 임시 방편의 setTimeout 함수 하나로 구성했음
이렇게 하면 데이터베이스로부터 걸리는 시간을 그나마 최적화하고, 로컬 서버단에서의 연산을 빠르게 해결하고 사용자에게 원하는 post 리스트를 보낼 수 있습니다. 

```javascript 
            let promiseOne=[];
            let promiseTwo=[];
            let postIdList=[];
            let postList=[];

            try{
            const friends = await prisma.user({id:userId}).following();
            promiseOne= friends.map(async ({id})=>{
                const likes = prisma.user({id}).likes();
                likes.then((likes)=>{
                    promiseTwo = likes.map(async ({id})=>{
                        const post = prisma.like({id}).post();
                        post.then((post)=>{
                            if(!postIdList.includes(post.id)){
                                postIdList.push(post.id);
                                postList.push(post);
                            }
                        })
                        await post; 
                    })
                })
                await likes;
            })
            await Promise.all([...promiseOne]);
            await Promise.all([...promiseTwo]);
```

**Comment by Songift** [comment]
async await이 아닌 promise까지 알아야 하는 이유. 
1. 기다리지 않는 상황 
2. 다수의 값을 await 하는 상황 
3. 스택 전체가 비동기화 되어야 하는 상황

**Comment by Songift** [comment]
내일 mdn 공식문서보면서 promise, await async 비동기 처리에 대한 정리를 하고 이해가 완료되면 스스로 암기를 해야겠다. 확실히해야하는 부분인 것 같습니다
